---
controller_credentials:
  - name: Automation Hub 
    description: Credential for Automation Hub 
    organization: Demo 
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      url: "https://console.redhat.com/api/automation-hub/content/published/"
      auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      token: "{{ lookup('ini', 'token section=galaxy_server.automation_hub file=ansible.cfg') }}"      

  - name: AWS
    description: AWS Credential from saml 
    organization: Demo  
    credential_type: Amazon Web Services
    inputs:
      username: "{{ lookup('ini', 'aws_access_key_id section=default file=~/.aws/credentials') }}"
      password: "{{ lookup('ini', 'aws_secret_access_key section=default file=~/.aws/credentials') }}"

  - name: Controller Credential
    description: Controller Credential to automate Controller itself 
    organization: Demo 
    credential_type: "Red Hat Ansible Automation Platform"
    inputs:
      username: "admin"
      password: "{{ admin_password }}"
      host: "https://controller.{{ top_level_domain }}"

  - name: AWS Windows 
    description: AWS Windows Machine Credential 
    organization: Windows 
    credential_type: Machine 
    inputs:
      username: administrator
      password: "{{ admin_password }}"
      become_method: runas 
      become_username: Administrator 
      become_password: "{{ admin_password }}"

  - name: AWS Linux 
    description: AWS Linux Machine Credential 
    organization: Linux 
    credential_type: Machine 
    kind: ssh
    inputs:
      username: ec2-user
      ssh_key_data: '' 
      become_method: ''
      become_username: ''

  - name: Automation Hub
    description: Automation Hub Credentials 
    organizations:
      - Demo
      - Windows 
      - Linux  
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      url: "https://console.redhat.com/api/automation-hub/"
      auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      token: "{{ lookup('ini', 'token section=galaxy_server.automation_hub file=ansible.cfg') }}"
