---
controller_credentials:
  - name: Automation Hub 
    description: Credential for Automation Hub 
    organization: Demo 
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      url: "https://console.redhat.com/api/automation-hub/content/published/"
      auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      token: "{{ lookup('ini', 'token section=galaxy_server.automation_hub file=ansible.cfg') }}"      

  - name: AWS
    description: AWS Credential from saml 
    organizations:
      - Demo 
      - Windows  
    credential_type: Amazon Web Services
    inputs:
      username: "{{ lookup('ini', 'aws_access_key_id section=default file=~/.aws/credentials') }}"
      password: "{{ lookup('ini', 'aws_secret_access_key section=default file=~/.aws/credentials') }}"