---
controller_credentials:
  - name: Automation Hub 
    description: Credential for Automation Hub 
    organization: Demo 
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      url: "https://console.redhat.com/api/automation-hub/content/published/"
      auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      token: "{{ lookup('ini', 'token section=galaxy_server.automation_hub file=ansible.cfg') }}"      