---
controller_inventories:
  - name: Linux Systems
    organization: Demo
    description: created by Ansible Playbook - for Linux Systems teams

  - name: Windows Systems
    organization: Windows
    description: created by Ansible Playbook - for Windows Systems teams

controller_inventory_sources:
  - name: Linux Systems
    source: ec2
    inventory: "Linux Systems"
    credential: AWS
    description: created by Ansible controller
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0




  # - name: Test Inventory - Smart
  #   organization: Default
  #   description: created by Ansible Playbook
  #   kind: smart
  #   host_filter:  "name__icontains=localhost"