---
controller_organizations:
- name: Demo
  description: Demo setup 
  galaxy_credentials:
    - "Automation Hub" 
    - "Ansible Galaxy"

- name: Windows
  description: Windows Team 
  galaxy_credentials:
    - "Automation Hub" 
    - "Ansible Galaxy"