---
controller_projects:
  - name: Demo Repo
    description: Demo repository
    organization: Demo
    scm_type: git
    scm_url: https://github.com/corumj/aap-demo.git
    scm_branch: main
    scm_clean: true
    scm_update_on_launch: false
    scm_credential: ""
    update_project: true
    wait: true

  - name: Windows Tasks
    description: Windows Tasks demo repository
    organization: Windows
    scm_type: git
    scm_url: https://github.com/corumj/ansible-windows-admin-tasks.git
    scm_branch: master
    scm_clean: true
    scm_update_on_launch: false
    scm_credential: ""
    update_project: true
    wait: false