---
controller_roles: 
  - user: alvaro 
    target_team: Infrastructure
    role: member 
    organizations: Demo 

  - user: gaverel
    target_team: Infrastructure
    role: member 
    organization: Demo

  - user: genly
    target_team: "Windows Admins"
    role: member 
    organization: Windows

  - target_team: Infrastructure 
    organizations: Demo
    role: admin

  - user: george
    target_team: "Windows Help Desk" 
    organizations: Windows 
    role: admin

  - user: raj
    target_team: "Networking" 
    organizations: Demo 
    role: admin