--- 
controller_teams:
  - name: Infrastructure
    description: SysAdmins 
    organization: Demo 
    state: present 
    
  - name: Infrastructure
    description: SysAdmins 
    organization: Windows 
    state: present 

  - name: Networking
    description: Network Admin Team 
    organization: Demo 
    state: present

  - name: Networking
    description: Network Admin Team 
    organization: Windows 
    state: present

  - name: Windows Admins
    description: Windows Admin Team 
    organization: Windows 
    state: present

  - name: Windows Help Desk
    description: Windows Help Desk Team 
    organization: Windows 
    state: present