---
# Override default dispatch roles for this environment 
controller_configuration_dispatcher_roles:
  - {role: settings, var: controller_settings, tags: settings}
  - {role: organizations, var: controller_organizations, tags: organizations}
  - {role: users, var: controller_user_accounts, tags: users}
  - {role: teams, var: controller_teams, tags: teams}
  - {role: credential_types, var: controller_credential_types, tags: credential_types}
  - {role: credentials, var: controller_credentials, tags: credentials}
  - {role: organizations, var: controller_organizations, tags: organizations}
  - {role: projects, var: controller_projects, tags: projects}
  - {role: inventories, var: controller_inventories, tags: inventories}
  - {role: inventory_sources, var: controller_inventory_sources, tags: inventory_sources}
  - {role: inventory_source_update, var: controller_inventory_sources, tags: inventory_sources}
  - {role: job_templates, var: controller_templates, tags: job_templates}
  - {role: workflow_job_templates, var: controller_workflows, tags: workflow_job_templates}
  # - {role: schedules, var: controller_schedules, tags: schedules}
  - {role: roles, var: controller_roles, tags: roles}
  # - {role: job_launch, var: controller_launch_jobs, tags: job_launch}
  # - {role: workflow_launch, var: controller_workflow_launch_jobs, tags: workflow_launch}
