---
controller_credentials:
  - name: Automation Hub 
    description: Credential for Automation Hub 
    organization: Default 
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      url: "https://console.redhat.com/api/automation-hub/"
      auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      token: "{{ hub_offline_token }}"      